apiVersion: v1
kind: Namespace
metadata:
  name: autoparts-production
  labels:
    app: autoparts
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: autoparts-staging
  labels:
    app: autoparts
    environment: staging
---
apiVersion: v1
kind: Secret
metadata:
  name: autoparts-secrets
  namespace: autoparts-production
type: Opaque
data:
  postgres-password: MTIzNDU2  # base64 encoded "123456"
  rabbitmq-password: YWRtaW4xMjM=  # base64 encoded "admin123"
  jwt-secret: c3VwZXItc2VjcmV0LWp3dC1rZXktZm9yLXByb2R1Y3Rpb24=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: autoparts-config
  namespace: autoparts-production
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Consul__Host: "consul"
  Consul__Port: "8500"
  UseRabbitMQ: "true"
  RabbitMQ__HostName: "rabbitmq"
  RabbitMQ__UserName: "admin"
  RabbitMQ__VirtualHost: "/"
  RabbitMQ__Port: "5672"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: autoparts-production
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: autoparts-production
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: autoparts-secrets
              key: postgres-password
        - name: POSTGRES_DB
          value: "AutoPartsDb"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command:
              - pg_isready
              - -U
              - postgres
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
              - pg_isready
              - -U
              - postgres
          initialDelaySeconds: 30
          periodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: autoparts-production
spec:
  selector:
    app: consul
  ports:
    - name: http
      port: 8500
      targetPort: 8500
    - name: dns-tcp
      port: 8600
      targetPort: 8600
      protocol: TCP
    - name: dns-udp
      port: 8600
      targetPort: 8600
      protocol: UDP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
  namespace: autoparts-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: hashicorp/consul:1.15
        command:
          - consul
          - agent
          - -server
          - -ui
          - -node=server-1
          - -bootstrap-expect=1
          - -client=0.0.0.0
        ports:
        - containerPort: 8500
        - containerPort: 8600
        readinessProbe:
          exec:
            command:
              - consul
              - members
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: autoparts-production
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: autoparts-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.12-management-alpine
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "admin"
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: autoparts-secrets
              key: rabbitmq-password
        - name: RABBITMQ_DEFAULT_VHOST
          value: "/"
        ports:
        - containerPort: 5672
        - containerPort: 15672
        readinessProbe:
          exec:
            command:
              - rabbitmq-diagnostics
              - ping
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
              - rabbitmq-diagnostics
              - ping
          initialDelaySeconds: 30
          periodSeconds: 10
